#!/usr/bin/env bash

# Get current brightness percentage
brightness=$(brightnessctl get)
max_brightness=$(brightnessctl max)
brightness_percent=$(( brightness * 100 / max_brightness ))

dunstify -a "Brightness" -t 1500 -r 1003 -h int:value:$brightness_percent "Brightness: ${brightness_percent}%"